repos:

  -   repo: local
      hooks:
      -   id: pyright
          name: pyright
          entry: pyright
          language: node
          pass_filenames: false
          types: [python]
          additional_dependencies: ['pyright@1.1.187']

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.28.1
    hooks:
      - id: markdownlint

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.3.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-toml
      - id: check-yaml
      - id: fix-byte-order-marker
      - id: check-added-large-files
      - id: detect-private-key
